version: '3'
services:
  frontend:
    restart: always
    build: .
    command: yarn --cwd frontend/client/ start
    volumes:
      - ./frontend/client:/app/

  node:
    restart: always
    command: node backend/index.js
    build: .
    ports:
      - "9090:5000"
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: